CREATE TABLE USUARIO(
ID_USUARIO	SERIAL PRIMARY KEY NOT NULL,
NOMBRE 		VARCHAR(20) NOT NULL,
APELLIDO 	VARCHAR(20) NOT NULL,
CEDULA 		VARCHAR(10) NOT NULL,
USUARIO		VARCHAR(10) NOT NULL,
CONTRASEÑA	VARCHAR(10) NOT NULL,
TIPO		INT NOT  NULL
);


CREATE TABLE MAQUINARIA(
ID_MAQUINARIA	SERIAL PRIMARY KEY NOT NULL,
CODIGO 		VARCHAR(20) NOT NULL PRIMARY KEY,
NOMBRE		VARCHAR(100) NOT NULL
);


CREATE TABLE MOLDE(
ID_MOLDE	SERIAL PRIMARY KEY NOT NULL,
CODIGO 		VARCHAR(40) NOT NULL PRIMARY KEY,
NOMBRE		VARCHAR(100) NOT NULL 
);


CREATE TABLE REPORTE(
ID_REPORTE 		SERIAL PRIMARY KEY NOT NULL,
FECHA			DATE NOT NULL,
ID_MAQUINARIA		INT,
ID_MOLDE		INT,
ID_USUARIO		INT NOT NULL,
DESCRIPCION_NOVEDAD	VARCHAR(500) NOT NULL,
TIPO_NOVEDAD		VARCHAR(20) NOT NULL,
DESCRIPCION_SOLUCION 	VARCHAR(500) NOT NULL,
TIPO_SOLUCION		VARCHAR(20) NOT NULL,
NOVEDAD			VARCHAR(100) NOT NULL,
FOTO			BYTEA,
REVISADO			VARCHAR(50) NOT NULL,
FOREIGN KEY (ID_MAQUINARIA) 	REFERENCES MAQUINARIA (ID_MAQUINARIA),
FOREIGN KEY (ID_MOLDE) 		REFERENCES MOLDE (ID_MOLDE),
FOREIGN KEY (ID_USUARIO) 	REFERENCES USUARIO (ID_USUARIO)
);


CREATE TABLE REPORTE_MOLDE(
ID_REPORTE 		SERIAL PRIMARY KEY NOT NULL,
FECHA			DATE NOT NULL,
ID_MAQUINARIA		INT,
ID_MOLDE		INT,
ID_USUARIO		INT NOT NULL,
DESCRIPCION_NOVEDAD	VARCHAR(500) NOT NULL,
TIPO_NOVEDAD		VARCHAR(20) NOT NULL,
DESCRIPCION_SOLUCION 	VARCHAR(500) NOT NULL,
TIPO_SOLUCION		VARCHAR(20) NOT NULL,
NOVEDAD			VARCHAR(100) NOT NULL,
FOTO			BYTEA,
ARTICULO		VARCHAR(30) NOT NULL,
REVISOR			VARCHAR(50) NOT NULL,
FOREIGN KEY (ID_MAQUINARIA) 	REFERENCES MAQUINARIA (ID_MAQUINARIA),
FOREIGN KEY (ID_MOLDE) 		REFERENCES MOLDE (ID_MOLDE),
FOREIGN KEY (ID_USUARIO) 	REFERENCES USUARIO (ID_USUARIO)
);