CREATE OR REPLACE FUNCTION INSERTAR_USUARIO(VARCHAR,VARCHAR,VARCHAR,VARCHAR,VARCHAR,INTEGER) RETURNS BOOLEAN AS $$
DECLARE
	CONTAR INTEGER;
BEGIN	
	CONTAR := COUNT(NOMBRE) FROM USUARIO WHERE USUARIO.CEDULA = $3;

	IF CONTAR = 0 THEN
		INSERT INTO USUARIO(NOMBRE,APELLIDO,CEDULA,USUARIO,CONTRASEÑA,TIPO) VALUES ($1,$2,$3,$4,$5,$6);
		RETURN TRUE;
	ELSE
		RETURN FALSE;
	END IF;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION INSERTAR_MAQUINARIA(VARCHAR,VARCHAR) RETURNS BOOLEAN AS $$
DECLARE
	CONTAR INTEGER;
BEGIN	
	CONTAR := COUNT(NOMBRE) FROM MAQUINARIA WHERE MAQUINARIA.CODIGO = $1;

	IF CONTAR = 0 THEN
		INSERT INTO MAQUINARIA(CODIGO,NOMBRE) VALUES ($1,$2);
		RETURN TRUE;
	ELSE
		RETURN FALSE;
	END IF;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION INSERTAR_MOLDE(VARCHAR,VARCHAR) RETURNS BOOLEAN AS $$
DECLARE
	CONTAR INTEGER;
BEGIN	
	CONTAR := COUNT(NOMBRE) FROM MOLDE WHERE MOLDE.CODIGO = $1;

	IF CONTAR = 0 THEN
		INSERT INTO MOLDE(CODIGO,NOMBRE) VALUES ($1,$2);
		RETURN TRUE;
	ELSE
		RETURN FALSE;
	END IF;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION AUTENTICACION(VARCHAR,VARCHAR) RETURNS BOOLEAN AS $$
DECLARE
	CONTAR INTEGER;
BEGIN
	CONTAR := COUNT(*) FROM USUARIO WHERE USUARIO.USUARIO = $1 AND USUARIO.CONTRASEÑA = $2;
	IF CONTAR = 1 THEN
		RETURN TRUE;
	ELSE
		RETURN FALSE;
	END IF;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION TODAS_MAQUINARIAS() RETURNS REFCURSOR AS $$
DECLARE
	MYCURS REFCURSOR;
BEGIN
	OPEN MYCURS FOR SELECT * FROM MAQUINARIA;
	RETURN MYCURS;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION TODOS_MOLDES() RETURNS REFCURSOR AS $$
DECLARE
	MYCURS REFCURSOR;
BEGIN
	OPEN MYCURS FOR SELECT * FROM MOLDE;
	RETURN MYCURS;
END;
$$ LANGUAGE PLPGSQL;


CREATE OR REPLACE FUNCTION TODOS_USUARIOS() RETURNS REFCURSOR AS $$
DECLARE
	MYCURS REFCURSOR;
BEGIN
	OPEN MYCURS FOR SELECT * FROM USUARIO;
	RETURN MYCURS;
END;
$$ LANGUAGE PLPGSQL;



