/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nuevoElemento;

import conexion.Conexion;
import java.sql.CallableStatement;
import java.sql.Connection;
import java.sql.Types;
import javax.swing.JOptionPane;

import validacion.ValidacionMaquinaria;

/**
 *
 * @author Angel
 */
public class InternalMaquinaria extends javax.swing.JInternalFrame {
    private ValidacionMaquinaria valMaquinaria;
    /**
     * Creates new form InternalMaquinaria
     */
    public InternalMaquinaria() {
        valMaquinaria = new ValidacionMaquinaria();
        initComponents();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtMaquinariaCodigo = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtMaquinariaNombre = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnMaquinariaCrear = new javax.swing.JButton();

        setClosable(true);
        setTitle("Nueva Maquinaria");

        txtMaquinariaCodigo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Codigo");

        txtMaquinariaNombre.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Nombre");

        btnMaquinariaCrear.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnMaquinariaCrear.setText("Crear");
        btnMaquinariaCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaquinariaCrearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(85, 85, 85)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnMaquinariaCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addGap(84, 84, 84)
                            .addComponent(txtMaquinariaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtMaquinariaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(117, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaquinariaCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMaquinariaNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(33, 33, 33)
                .addComponent(btnMaquinariaCrear)
                .addContainerGap(51, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMaquinariaCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaquinariaCrearActionPerformed
        // TODO add your handling code here:
        if(valMaquinaria.camposVacios(txtMaquinariaCodigo, txtMaquinariaNombre) == false){
            Conexion conexion =  new Conexion();
            Connection conn = conexion.Conexion();
            try{
                CallableStatement insertar_maquinaria =  conn.prepareCall("{ ? = call INSERTAR_MAQUINARIA ( ? , ? ) }");
                insertar_maquinaria.registerOutParameter(1, Types.BOOLEAN);
                insertar_maquinaria.setString(2, txtMaquinariaCodigo.getText());
                insertar_maquinaria.setString(3, txtMaquinariaNombre.getText());
                insertar_maquinaria.execute();
                boolean res = insertar_maquinaria.getBoolean(1);
                insertar_maquinaria.close();
                if(res == true){
                    JOptionPane.showConfirmDialog(this, "Maquinaria creado con exito", "Mensaje",JOptionPane.CLOSED_OPTION);
                }
                else{
                    JOptionPane.showConfirmDialog(this, "La Maquinaria ya existe", "Mensaje",JOptionPane.CLOSED_OPTION);
                }
                
            }catch(Exception e){
                System.out.println("Error: "+e.getMessage());
                JOptionPane.showConfirmDialog(this, "No de be dejar campos vacios", "Error",JOptionPane.CLOSED_OPTION);
            }
        }
        else{
            JOptionPane.showConfirmDialog(this, "Fallo al crear Maquinaria", "Error",JOptionPane.CLOSED_OPTION);
        }
        
    }//GEN-LAST:event_btnMaquinariaCrearActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMaquinariaCrear;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtMaquinariaCodigo;
    private javax.swing.JTextField txtMaquinariaNombre;
    // End of variables declaration//GEN-END:variables
}
